server:
  port: 50045
spring:
  application:
    name: deneme-service
  profiles:
    active: default
  datasource:
    hikari:
      username: postgres
      password: MYPASSWD
      maximum-pool-size: 50
      minimum-idle: 20
      connection-timeout: 20500
    url: jdbc:postgresql://localhost:5432/postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: info

